lable2host = {
    'tail': {
        'family': {
            0: 'Mycobacteriaceae',
            1: 'Streptococcaceae',
            2: 'Gordoniaceae',
            3: 'Bacillaceae',
            4: 'Vibrionaceae',
            5: 'Microbacteriaceae',
            6: 'Streptomycetaceae',
            7: 'Micrococcaceae',
            8: 'Aeromonadaceae',
            9: 'Lactobacillaceae',
            10: 'Erwiniaceae',
            11: 'Pseudomonadaceae',
            12: 'Enterococcaceae',
            13: 'Propionibacteriaceae',
            14: 'Synechococcaceae',
            15: 'Pectobacteriaceae',
            16: 'Burkholderiaceae',
            17: 'Moraxellaceae',
            18: 'Nocardiaceae',
            19: 'Morganellaceae',
            20: 'Staphylococcaceae',
            21: 'Listeriaceae',
            22: 'Alcaligenaceae',
            23: 'Pasteurellaceae',
            24: 'Paenibacillaceae',
            25: 'Caulobacteraceae',
            26: 'Corynebacteriaceae',
            27: 'Flavobacteriaceae',
            28: 'Pseudoalteromonadaceae',
            29: 'Roseobacteraceae',
            30: 'Pelagibacteraceae',
            31: 'Rhodobacteraceae',
            32: 'Oscillospiraceae',
            33: 'Peptostreptococcaceae',
            34: 'Shewanellaceae',
            35: 'Helicobacteraceae',
            36: 'Bifidobacteriaceae'
        },
        'genus': {
            0: 'Mycolicibacterium',
            1: 'Streptococcus',
            2: 'Gordonia',
            3: 'Bacillus',
            4: 'Vibrio',
            5: 'Lactococcus',
            6: 'Microbacterium',
            7: 'Streptomyces',
            8: 'Aeromonas',
            9: 'Arthrobacter',
            10: 'Pseudomonas',
            11: 'Enterococcus',
            12: 'Synechococcus',
            13: 'Cutibacterium',
            14: 'Campylobacter',
            15: 'Serratia',
            16: 'Pectobacterium',
            17: 'Rhodococcus',
            18: 'Klebsiella',
            19: 'Staphylococcus',
            20: 'Listeria',
            21: 'Proteus',
            22: 'Ralstonia',
            23: 'Moraxella',
            24: 'Xanthomonas',
            25: 'Lactobacillus',
            26: 'Achromobacter',
            27: 'Lactiplantibacillus',
            28: 'Dickeya',
            29: 'Caulobacter',
            30: 'Corynebacterium',
            31: 'Paenibacillus',
            32: 'Rhizobium',
            33: 'Pseudoalteromonas',
            34: 'Lacticaseibacillus',
            35: 'Candidatus Pelagibacter',
            36: 'Faecalibacterium',
            37: 'Acinetobacter',
            38: 'Clostridioides',
            39: 'Mannheimia',
            40: 'Cellulophaga',
            41: 'Levilactobacillus',
            42: 'Agrobacterium',
            43: 'Leuconostoc',
            44: 'Shewanella',
            45: 'Helicobacter',
            46: 'Limosilactobacillus',
            47: 'Prochlorococcus',
            48: 'Rhodobacter',
            49: 'Bifidobacterium',
            50: 'Ruegeria',
            51: 'Brevibacillus',
            52: 'Brucella',
            53: 'Flavobacterium'
        },
        'species': {
            0: 'Mycolicibacterium smegmatis',
            1: 'Gordonia terrae',
            2: 'Lactococcus lactis',
            3: 'Streptococcus thermophilus',
            4: 'Arthrobacter sp. ATCC 21022',
            5: 'Microbacterium foliorum',
            6: 'Erwinia amylovora',
            7: 'Cutibacterium acnes',
            8: 'Pseudomonas aeruginosa',
            9: 'Enterococcus faecalis',
            10: 'Streptomyces griseus',
            11: 'Bacillus subtilis',
            12: 'Streptococcus pneumoniae',
            13: 'Vibrio cholerae',
            14: 'Staphylococcus aureus',
            15: 'Listeria monocytogenes',
            16: 'Moraxella catarrhalis',
            17: 'Rhodococcus erythropolis',
            18: 'Microbacterium paraoxydans',
            19: 'Klebsiella pneumoniae',
            20: 'Yersinia enterocolitica',
            21: 'Proteus mirabilis',
            22: 'Lactiplantibacillus plantarum',
            23: 'Achromobacter xylosoxidans',
            24: 'Caulobacter vibrioides',
            25: 'Bacillus pumilus',
            26: 'Paenibacillus larvae',
            27: 'Pectobacterium atrosepticum',
            28: 'Serratia sp. ATCC 39006',
            29: 'Streptococcus equinus',
            30: 'Lactobacillus delbrueckii',
            31: 'Faecalibacterium prausnitzii',
            32: 'Acinetobacter baumannii',
            33: 'Clostridioides difficile',
            34: 'Mannheimia haemolytica',
            35: 'Cellulophaga baltica',
            36: 'Levilactobacillus brevis',
            37: 'Agrobacterium tumefaciens',
            38: 'Candidatus Pelagibacter ubique',
            39: 'Lacticaseibacillus paracasei',
            40: 'Vibrio anguillarum',
            41: 'Xanthomonas oryzae',
            42: 'Pasteurella multocida',
            43: 'Rhodococcus hoagii',
            44: 'Helicobacter pylori',
            45: 'Rhizobium leguminosarum',
            46: 'Prochlorococcus marinus',
            47: 'Rhodobacter capsulatus',
            48: 'Corynebacterium vitaeruminis',
            49: 'Ruegeria pomeroyi',
            50: 'Pseudoalteromonas marina',
            51: 'Corynebacterium xerosis',
            52: 'Pseudomonas syringae',
            53: 'Sinorhizobium meliloti',
            54: 'Shewanella sp.',
            55: 'Leuconostoc mesenteroides'
        }
    },
    'lysin': {
        'family': {
            0: 'Streptococcaceae',
            1: 'Vibrionaceae',
            2: 'Pseudomonadaceae',
            3: 'Aeromonadaceae',
            4: 'Thermaceae',
            5: 'Streptomycetaceae',
            6: 'Burkholderiaceae',
            7: 'Prochlorococcaceae',
            8: 'Bacillaceae',
            9: 'Lactobacillaceae',
            10: 'Erwiniaceae',
            11: 'Listeriaceae',
            12: 'Mycobacteriaceae',
            13: 'Synechococcaceae',
            14: 'Xanthomonadaceae',
            15: 'Morganellaceae',
            16: 'Enterococcaceae',
            17: 'Roseobacteraceae',
            18: 'Microbacteriaceae',
            19: 'Comamonadaceae',
            20: 'Gordoniaceae',
            21: 'Campylobacteraceae',
            22: 'Nocardiaceae',
            23: 'Rhodobacteraceae',
            24: 'Propionibacteriaceae',
            25: 'Caulobacteraceae',
            26: 'Pectobacteriaceae',
            27: 'Staphylococcaceae',
            28: 'Pseudoalteromonadaceae',
            29: 'Flavobacteriaceae',
            30: 'Paenibacillaceae',
            31: 'Micrococcaceae',
            32: 'Alcaligenaceae',
            33: 'Rhizobiaceae',
            34: 'Corynebacteriaceae',
            35: 'Peptostreptococcaceae',
            36: 'Prevotellaceae'
        },
        'genus': {
            0: 'Lactococcus',
            1: 'Vibrio',
            2: 'Pseudomonas',
            3: 'Aeromonas',
            4: 'Thermus',
            5: 'Streptococcus',
            6: 'Streptomyces',
            7: 'Burkholderia',
            8: 'Prochlorococcus',
            9: 'Bacillus',
            10: 'Lacticaseibacillus',
            11: 'Erwinia',
            12: 'Lactobacillus',
            13: 'Listeria',
            14: 'Mycolicibacterium',
            15: 'Synechococcus',
            16: 'Xanthomonas',
            17: 'Enterococcus',
            18: 'Klebsiella',
            19: 'Gordonia',
            20: 'Campylobacter',
            21: 'Rhodococcus',
            22: 'Leuconostoc',
            23: 'Cutibacterium',
            24: 'Acinetobacter',
            25: 'Caulobacter',
            26: 'Pectobacterium',
            27: 'Lactiplantibacillus',
            28: 'Staphylococcus',
            29: 'Pseudoalteromonas',
            30: 'Cellulophaga',
            31: 'Flavobacterium',
            32: 'Paenibacillus',
            33: 'Arthrobacter',
            34: 'Achromobacter',
            35: 'Proteus',
            36: 'Dickeya',
            37: 'Corynebacterium',
            38: 'Clostridioides',
            39: 'Microbacterium',
            40: 'Prevotella',
            41: 'Priestia'
        },
        'species': {
            0: 'Lactococcus lactis',
            1: 'Aeromonas salmonicida',
            2: 'Vibrio parahaemolyticus',
            3: 'Vibrio cholerae',
            4: 'Pseudomonas aeruginosa',
            5: 'Prochlorococcus marinus',
            6: 'Streptococcus thermophilus',
            7: 'Streptococcus suis',
            8: 'Erwinia amylovora',
            9: 'Bacillus thuringiensis',
            10: 'Listeria monocytogenes',
            11: 'Mycolicibacterium smegmatis',
            12: 'Burkholderia cenocepacia',
            13: 'Bacillus subtilis',
            14: 'Enterococcus faecalis',
            15: 'Klebsiella pneumoniae',
            16: 'Gordonia terrae',
            17: 'Streptococcus pneumoniae',
            18: 'Campylobacter jejuni',
            19: 'Gordonia rubripertincta',
            20: 'Rhodococcus erythropolis',
            21: 'Cutibacterium acnes',
            22: 'Caulobacter vibrioides',
            23: 'Lactiplantibacillus plantarum',
            24: 'Stenotrophomonas maltophilia',
            25: 'Bacillus pumilus',
            26: 'Pectobacterium atrosepticum',
            27: 'Staphylococcus aureus',
            28: 'Cellulophaga baltica',
            29: 'Streptomyces lividans',
            30: 'Paenibacillus larvae',
            31: 'Achromobacter xylosoxidans',
            32: 'Sinorhizobium meliloti',
            33: 'Proteus mirabilis',
            34: 'Streptococcus agalactiae',
            35: 'Streptococcus pyogenes',
            36: 'Citrobacter freundii',
            37: 'Arthrobacter sp. ATCC 21022',
            38: 'Streptomyces griseus',
            39: 'Levilactobacillus brevis',
            40: 'Clostridioides difficile',
            41: 'Dickeya solani',
            42: 'Microbacterium foliorum',
            43: 'Microbacterium paraoxydans',
            44: 'Prevotella sp.',
            45: 'Priestia megaterium',
            46: 'Arthrobacter globiformis'
        }
    }
}