species2genus = {
    'Unknown': 'Unknown',
    'Streptococcus thermophilus': 'Streptococcus',
    'Escherichia coli': 'Escherichia',
    'Listeria monocytogenes': 'Listeria',
    'Phaeobacter inhibens': 'Phaeobacter',
    'Aeromonas hydrophila': 'Aeromonas',
    'Vibrio parahaemolyticus': 'Vibrio',
    'Xanthomonas campestris': 'Xanthomonas',
    'Vibrio alginolyticus': 'Vibrio',
    'Achromobacter marplatensis': 'Achromobacter',
    'Bacillus cereus': 'Bacillus',
    'Aeromonas salmonicida': 'Aeromonas',
    'Mesorhizobium loti': 'Mesorhizobium',
    'Pantoea agglomerans': 'Pantoea',
    'Xylella fastidiosa': 'Xylella',
    'Mycolicibacterium smegmatis': 'Mycolicibacterium',
    'Gordonia terrae': 'Gordonia',
    'Arthrobacter sp. ATCC 21022': 'Arthrobacter',
    'Streptomyces griseofuscus': 'Streptomyces',
    'Microbacterium foliorum': 'Microbacterium',
    'Enterococcus faecalis': 'Enterococcus',
    'Citrobacter rodentium': 'Citrobacter',
    'Escherichia sp. MOD1-EC6098': 'Escherichia',
    'Vibrio harveyi': 'Vibrio',
    'Streptomyces sanglieri': 'Streptomyces',
    'Arthrobacter globiformis': 'Arthrobacter',
    'Proteus mirabilis': 'Proteus',
    'Salmonella enterica': 'Salmonella',
    'Klebsiella pneumoniae': 'Klebsiella',
    'Stenotrophomonas maltophilia': 'Stenotrophomonas',
    'Synechococcus sp. MW02': 'Synechococcus',
    'Parasynechococcus marenigrum': 'Parasynechococcus',
    'Serratia sp. ATCC 39006': 'Serratia',
    'Elizabethkingia anophelis': 'Elizabethkingia',
    'Lactococcus lactis': 'Lactococcus',
    'Salmonella sp.': 'Salmonella',
    'Mycobacterium sp.': 'Mycobacterium',
    'Microbacterium paraoxydans': 'Microbacterium',
    'Rhodococcus erythropolis': 'Rhodococcus',
    'Tenacibaculum geojense': 'Tenacibaculum',
    'Pseudoalteromonas hodoensis': 'Pseudoalteromonas',
    'Pseudoalteromonas marina': 'Pseudoalteromonas',
    'Citrobacter freundii': 'Citrobacter',
    'Ochrobactrum sp. POC9': 'Ochrobactrum',
    'Vibrio cholerae': 'Vibrio',
    'Sporosarcina aquimarina': 'Sporosarcina',
    'Bifidobacterium asteroides': 'Bifidobacterium',
    'Edwardsiella tarda': 'Edwardsiella',
    'Brucella abortus': 'Brucella',
    'Streptomyces lividans': 'Streptomyces',
    'Alteromonas sp.': 'Alteromonas',
    'Paenibacillus larvae': 'Paenibacillus',
    'Enterobacter cloacae': 'Enterobacter',
    'Enterobacter hormaechei': 'Enterobacter',
    'Sphaerotilus natans': 'Sphaerotilus',
    'Flavobacterium columnare': 'Flavobacterium',
    'Bacillus safensis': 'Bacillus',
    'Brevundimonas subvibrioides': 'Brevundimonas',
    'Butyrivibrio fibrisolvens': 'Butyrivibrio',
    'Pseudomonas syringae': 'Pseudomonas',
    'Pectobacterium carotovorum': 'Pectobacterium',
    'Shigella sonnei': 'Shigella',
    'Geobacillus kaustophilus': 'Geobacillus',
    'Shigella flexneri': 'Shigella',
    'Flavobacterium sp. LMO8': 'Flavobacterium',
    'Flavobacterium sp. LMO9': 'Flavobacterium',
    'Flavobacterium sp. LMO6': 'Flavobacterium',
    'Cutibacterium acnes': 'Cutibacterium',
    'Sinomonas atrocyanea': 'Sinomonas',
    'Pectobacterium wasabiae': 'Pectobacterium',
    'Pectobacterium atrosepticum': 'Pectobacterium',
    'Xanthomonas oryzae': 'Xanthomonas',
    'Candidatus Pelagibacter sp. HTCC7211': 'Candidatus Pelagibacter',
    'Candidatus Pelagibacter sp. FZCC0015': 'Candidatus Pelagibacter',
    'Rhizobium leguminosarum': 'Rhizobium',
    'Photobacterium damselae': 'Photobacterium',
    'Alteromonas litorea': 'Alteromonas',
    'Pseudomonas aeruginosa': 'Pseudomonas',
    'Erwinia amylovora': 'Erwinia',
    'Vibrio mediterranei': 'Vibrio',
    'Vibrio variabilis': 'Vibrio',
    'Rhodobacteraceae bacterium': '',
    'Campylobacter jejuni': 'Campylobacter',
    'Burkholderia thailandensis': 'Burkholderia',
    'Lactococcus cremoris': 'Lactococcus',
    'Leuconostoc pseudomesenteroides': 'Leuconostoc',
    'Leuconostoc mesenteroides': 'Leuconostoc',
    'Gordonia rubripertincta': 'Gordonia',
    'Corynebacterium flavescens': 'Corynebacterium',
    'Streptomyces griseus': 'Streptomyces',
    'Mycobacteroides abscessus': 'Mycobacteroides',
    'Klebsiella aerogenes': 'Klebsiella',
    'Bacillus pumilus': 'Bacillus',
    'Yersinia enterocolitica': 'Yersinia',
    'Citrobacter amalonaticus': 'Citrobacter',
    'Erwinia persicina': 'Erwinia',
    'Serratia marcescens': 'Serratia',
    'Bacillus subtilis': 'Bacillus',
    'Xanthomonas vesicatoria': 'Xanthomonas',
    'Vibrio owensii': 'Vibrio',
    'Bacillus thuringiensis': 'Bacillus',
    'Ralstonia solanacearum': 'Ralstonia',
    'Streptomyces scabiei': 'Streptomyces',
    'Rothia dentocariosa': 'Rothia',
    'Mycolicibacterium aichiense': 'Mycolicibacterium',
    'Gordonia westfalica': 'Gordonia',
    'Corynebacterium vitaeruminis': 'Corynebacterium',
    'Achromobacter denitrificans': 'Achromobacter',
    'Erwinia pyrifoliae': 'Erwinia',
    'Curvibacter sp. AEP1.3': 'Curvibacter',
    'Burkholderia pseudomallei': 'Burkholderia',
    'Sinorhizobium meliloti': 'Sinorhizobium',
    'Streptococcus suis': 'Streptococcus',
    'Pseudomonas putida': 'Pseudomonas',
    'Aeromonas rivipollensis': 'Aeromonas',
    'Xanthomonas sp.': 'Xanthomonas',
    'Bacillus sp. (in: Bacteria)': 'Bacillus',
    'Vibrio natriegens': 'Vibrio',
    'Xanthomonas citri': 'Xanthomonas',
    'Bordetella bronchiseptica': 'Bordetella',
    'Shigella boydii': 'Shigella',
    'Priestia megaterium': 'Priestia',
    'Bacillus velezensis': 'Bacillus',
    'Streptomyces xanthochromogenes': 'Streptomyces',
    'Streptomyces tricolor': 'Streptomyces',
    'Vibrio anguillarum': 'Vibrio',
    'Streptomyces platensis': 'Streptomyces',
    'Corynebacterium xerosis': 'Corynebacterium',
    'Achromobacter xylosoxidans': 'Achromobacter',
    'Achromobacter animicus': 'Achromobacter',
    'Caulobacter vibrioides': 'Caulobacter',
    'Acinetobacter baumannii': 'Acinetobacter',
    'Dinoroseobacter shibae': 'Dinoroseobacter',
    'Vibrio campbellii': 'Vibrio',
    'Bifidobacterium thermophilum': 'Bifidobacterium',
    'Candidatus Pelagibacter ubique': 'Candidatus Pelagibacter',
    'Levilactobacillus brevis': 'Levilactobacillus',
    'Rheinheimera sp. BAL341': 'Rheinheimera',
    'Shewanella inventionis': 'Shewanella',
    'Pseudomonas lactis': 'Pseudomonas',
    'Ligilactobacillus murinus': 'Ligilactobacillus',
    'Shigella dysenteriae': 'Shigella',
    'Gordonia neofelifaecis': 'Gordonia',
    'Microbacterium natoriense': 'Microbacterium',
    'Streptomyces mirabilis': 'Streptomyces',
    'Streptococcus constellatus': 'Streptococcus',
    'Streptococcus cristatus': 'Streptococcus',
    'Streptococcus agalactiae': 'Streptococcus',
    'Streptococcus dysgalactiae': 'Streptococcus',
    'Streptococcus entericus': 'Streptococcus',
    'Streptococcus equi': 'Streptococcus',
    'Streptococcus acidominimus': 'Streptococcus',
    'Streptococcus equinus': 'Streptococcus',
    'Streptococcus gallolyticus': 'Streptococcus',
    'Streptococcus gordonii': 'Streptococcus',
    'Streptococcus halotolerans': 'Streptococcus',
    'Streptococcus himalayensis': 'Streptococcus',
    'Streptococcus hyovaginalis': 'Streptococcus',
    'Streptococcus infantarius': 'Streptococcus',
    'Streptococcus infantis': 'Streptococcus',
    'Streptococcus iniae': 'Streptococcus',
    'Streptococcus intermedius': 'Streptococcus',
    'Streptococcus lutetiensis': 'Streptococcus',
    'Streptococcus macedonicus': 'Streptococcus',
    'Streptococcus marmotae': 'Streptococcus',
    'Streptococcus merionis': 'Streptococcus',
    'Streptococcus mitis': 'Streptococcus',
    'Streptococcus oralis': 'Streptococcus',
    'Streptococcus parasanguinis': 'Streptococcus',
    'Streptococcus parauberis': 'Streptococcus',
    'Streptococcus pasteurianus': 'Streptococcus',
    'Streptococcus phocae': 'Streptococcus',
    'Streptococcus plurextorum': 'Streptococcus',
    'Streptococcus pseudopneumoniae': 'Streptococcus',
    'Streptococcus pseudoporcinus': 'Streptococcus',
    'Streptococcus pyogenes': 'Streptococcus',
    'Streptococcus salivarius': 'Streptococcus',
    'Streptococcus sanguinis': 'Streptococcus',
    'Streptococcus anginosus': 'Streptococcus',
    'Streptococcus uberis': 'Streptococcus',
    'Streptococcus urinalis': 'Streptococcus',
    'Streptococcus vestibularis': 'Streptococcus',
    'Streptococcus pneumoniae': 'Streptococcus',
    'Streptococcus caballi': 'Streptococcus',
    'Streptococcus canis': 'Streptococcus',
    'Streptococcus castoreus': 'Streptococcus',
    'Streptococcus henryi': 'Streptococcus',
    'Streptococcus ictaluri': 'Streptococcus',
    'Streptococcus orisratti': 'Streptococcus',
    'Streptococcus porcinus': 'Streptococcus',
    'Streptococcus azizii': 'Streptococcus',
    'Streptococcus cuniculi': 'Streptococcus',
    'Streptococcus porci': 'Streptococcus',
    'Streptococcus thoraltensis': 'Streptococcus',
    'Burkholderia cenocepacia': 'Burkholderia',
    'Gammaproteobacteria bacterium': '',
    'Nodularia spumigena': 'Nodularia',
    'Aeromonas sobria': 'Aeromonas',
    'Agrobacterium tumefaciens': 'Agrobacterium',
    'Shewanella indica': 'Shewanella',
    'Phocaeicola dorei': 'Phocaeicola',
    'Synechococcus sp. WH 7803': 'Synechococcus',
    'Virgibacillus halotolerans': 'Virgibacillus',
    'Exiguobacterium aurantiacum': 'Exiguobacterium',
    'Pseudomonas sp.': 'Pseudomonas',
    'Fusobacterium nucleatum': 'Fusobacterium',
    'Microcystis aeruginosa': 'Microcystis',
    'Cronobacter turicensis': 'Cronobacter',
    'Vibrio sp.': 'Vibrio',
    'Meiothermus sp.': 'Meiothermus',
    'Thermus sp. TC4': 'Thermus',
    'Streptomyces venezuelae': 'Streptomyces',
    'Enterococcus faecium': 'Enterococcus',
    'Pseudoalteromonas atlantica': 'Pseudoalteromonas',
    'Providencia stuartii': 'Providencia',
    'Thermobifida fusca': 'Thermobifida',
    'Alteromonas macleodii': 'Alteromonas',
    'Vibrio maritimus': 'Vibrio',
    'Prevotella sp.': 'Prevotella',
    'Thermus thermophilus': 'Thermus',
    'Paracoccus versutus': 'Paracoccus',
    'Paracoccus kondratievae': 'Paracoccus',
    'Paracoccus sulfuroxidans': 'Paracoccus',
    'Paracoccus thiocyanatus': 'Paracoccus',
    'Paracoccus yeei': 'Paracoccus',
    'Shigella sp.': 'Shigella',
    'Alkalihalobacillus pseudalcaliphilus': 'Alkalihalobacillus',
    'Lactiplantibacillus plantarum': 'Lactiplantibacillus',
    'Aeromonas schubertii': 'Aeromonas',
    'Aerococcus viridans': 'Aerococcus',
    'Vibrio vulnificus': 'Vibrio',
    'Yersinia pseudotuberculosis': 'Yersinia',
    'Microcystis elabens': 'Microcystis',
    'Vibrio sagamiensis': 'Vibrio',
    'Xanthomonas euvesicatoria': 'Xanthomonas',
    'Lacticaseibacillus rhamnosus': 'Lacticaseibacillus',
    'Brevibacterium fuscum': 'Brevibacterium',
    'Sutcliffiella cohnii': 'Sutcliffiella',
    'Alkalihalobacillus bogoriensis': 'Alkalihalobacillus',
    'Exiguobacterium alkaliphilum': 'Exiguobacterium',
    'Alkalihalobacillus pseudofirmus': 'Alkalihalobacillus',
    'Edwardsiella anguillarum': 'Edwardsiella',
    'Weissella ceti': 'Weissella',
    'Dickeya solani': 'Dickeya',
    'Paeniglutamicibacter sulfureus': 'Paeniglutamicibacter',
    'Limosilactobacillus reuteri': 'Limosilactobacillus',
    'Cronobacter sakazakii': 'Cronobacter',
    'Bacillus amyloliquefaciens': 'Bacillus',
    'Acidovorax citrulli': 'Acidovorax',
    'Bacillus anthracis': 'Bacillus',
    'bacterium': 'unclassified Bacteria',
    'Vibrio coralliilyticus': 'Vibrio',
    'Streptomyces virginiae': 'Streptomyces',
    'Bacteroides intestinalis': 'Bacteroides',
    'Mastigocladus sp.': 'Mastigocladus',
    'Leptospira biflexa': 'Leptospira',
    'Eggerthella lenta': 'Eggerthella',
    'Ruegeria pomeroyi': 'Ruegeria',
    'Synechococcus sp. WH 8109': 'Synechococcus',
    'Erwinia tracheiphila': 'Erwinia',
    'Lactococcus garvieae': 'Lactococcus',
    'Pasteurella multocida': 'Pasteurella',
    'Streptomyces toxytricini': 'Streptomyces',
    'Alteromonas marina': 'Alteromonas',
    'Pseudomonas fluorescens': 'Pseudomonas',
    'Oenococcus oeni': 'Oenococcus',
    'Streptococcus sp.': 'Streptococcus',
    'Dickeya dadantii': 'Dickeya',
    'Marinomonas sp.': 'Marinomonas',
    'Clostridioides difficile': 'Clostridioides',
    'Microbacterium terrae': 'Microbacterium',
    'Mycolicibacterium phlei': 'Mycolicibacterium',
    'Anoxybacillus caldiproteolyticus': 'Anoxybacillus',
    'Bacillus mycoides': 'Bacillus',
    'Xanthomonas fragariae': 'Xanthomonas',
    'Lacticaseibacillus paracasei': 'Lacticaseibacillus',
    'Lactobacillus delbrueckii': 'Lactobacillus',
    'Schaalia odontolytica': 'Schaalia',
    'Streptomyces viridochromogenes': 'Streptomyces',
    'Nocardia transvalensis': 'Nocardia',
    'Faecalibacterium prausnitzii': 'Faecalibacterium',
    'Pontimonas salivibrio': 'Pontimonas',
    'Gluconobacter cerinus': 'Gluconobacter',
    'Staphylococcus aureus': 'Staphylococcus',
    'Salinibacter ruber': 'Salinibacter',
    'Erysipelothrix rhusiopathiae': 'Erysipelothrix',
    'Proteus penneri': 'Proteus',
    'Plesiomonas sp.': 'Plesiomonas',
    'Synechococcus sp. TCC793': 'Synechococcus',
    'Streptomyces azureus': 'Streptomyces',
    'Pseudoalteromonas sp.': 'Pseudoalteromonas',
    'Raoultella ornithinolytica': 'Raoultella',
    'Citromicrobium sp. RCC1878': 'Citromicrobium',
    'Aphanizomenon flos-aquae': 'Aphanizomenon',
    'Pectobacterium sp.': 'Pectobacterium',
    'Lysinibacillus sphaericus': 'Lysinibacillus',
    'Vibrio splendidus': 'Vibrio',
    'Pseudoalteromonas phenolica': 'Pseudoalteromonas',
    'Lacticaseibacillus casei': 'Lacticaseibacillus',
    'Lactiplantibacillus pentosus': 'Lactiplantibacillus',
    'Sinorhizobium sp. LM21': 'Sinorhizobium',
    'Caldibacillus debilis': 'Caldibacillus',
    'Leclercia adecarboxylata': 'Leclercia',
    'Arthrobacter sp.': 'Arthrobacter',
    'Brevibacterium iodinum': 'Brevibacterium',
    'Salicola sp. PV4': 'Salicola',
    'Dickeya fangzhongdai': 'Dickeya',
    'Brucella anthropi': 'Brucella',
    'Brucella intermedia': 'Brucella',
    'Candidatus Xenohaliotis californiensis': 'Candidatus Xenohaliotis',
    'Tritonibacter mobilis': 'Tritonibacter',
    'Bradyrhizobium diazoefficiens': 'Bradyrhizobium',
    'Corynebacterium pseudotuberculosis': 'Corynebacterium',
    'Morganella morganii': 'Morganella',
    'Staphylococcus warneri': 'Staphylococcus',
    'Corynebacterium simulans': 'Corynebacterium',
    'Shewanella putrefaciens': 'Shewanella',
    'Sphingobium sp. IP1': 'Sphingobium',
    'Rhodococcus opacus': 'Rhodococcus',
    'Aeromonas sp.': 'Aeromonas',
    'Marinomonas mediterranea': 'Marinomonas',
    'Brucella sp.': 'Brucella',
    'Synechococcus sp.': 'Synechococcus',
    'Shewanella baltica': 'Shewanella',
    'Candidatus Azobacteroides pseudotrichonymphae': 'Candidatus Azobacteroides',
    'Serratia rubidaea': 'Serratia',
    'Geobacillus stearothermophilus': 'Geobacillus',
    'Listeria weihenstephanensis': 'Listeria',
    'Providencia sp.': 'Providencia',
    'Helicobacter pylori': 'Helicobacter',
    'Corynebacterium glutamicum': 'Corynebacterium',
    'Rathayibacter toxicus': 'Rathayibacter',
    'Erythrobacter litoralis': 'Erythrobacter',
    'Flavobacterium sp. B183': 'Flavobacterium',
    'Proteus vulgaris': 'Proteus',
    'Aquamicrobium sp. H14': 'Aquamicrobium',
    'Aeribacillus pallidus': 'Aeribacillus',
    'Xanthomonas arboricola': 'Xanthomonas',
    'Streptomyces coelicolor': 'Streptomyces',
    'Halomonas ventosae': 'Halomonas',
    'Alteromonas gracilis': 'Alteromonas',
    'Aeromonas sp. ARM81': 'Aeromonas',
    'Salinivibrio sp.': 'Salinivibrio',
    'Propionibacterium freudenreichii': 'Propionibacterium',
    'Leptospira inadai': 'Leptospira',
    'Salipiger profundus': 'Salipiger',
    'Flavobacterium psychrophilum': 'Flavobacterium',
    'Weissella sp.': 'Weissella',
    'Rhodovulum sp. P5': 'Rhodovulum',
    'Shewanella fidelis': 'Shewanella',
    'Enterobacter sp. CT7': 'Enterobacter',
    'Morganella sp. (in: Bacteria)': 'Morganella',
    'Pseudoalteromonas sp. H6': 'Pseudoalteromonas',
    'Gordonia alkanivorans': 'Gordonia',
    'Gordonia malaquae': 'Gordonia',
    'Tsukamurella paurometabola': 'Tsukamurella',
    'Marinitoga camini': 'Marinitoga',
    'Brucella inopinata': 'Brucella',
    'Acaryochloris marina': 'Acaryochloris',
    'Vibrio metschnikovii': 'Vibrio',
    'Sutcliffiella halmapala': 'Sutcliffiella',
    'Cellulophaga baltica': 'Cellulophaga',
    'Streptomyces avermitilis': 'Streptomyces',
    'Moraxella catarrhalis': 'Moraxella',
    'Alkalihalobacillus alcalophilus': 'Alkalihalobacillus',
    'Vibrio ordalii': 'Vibrio',
    'Skermania piniformis': 'Skermania',
    'Streptomyces flavovirens': 'Streptomyces',
    'Caulobacter sp.': 'Caulobacter',
    'Citrobacter sp.': 'Citrobacter',
    'Mannheimia haemolytica': 'Mannheimia',
    'Brevibacillus laterosporus': 'Brevibacillus',
    'Rhodobacter capsulatus': 'Rhodobacter',
    'Cronobacter sp.': 'Cronobacter',
    'Vibrio kanaloae': 'Vibrio',
    'Streptococcus mutans': 'Streptococcus',
    'Tsukamurella inchonensis': 'Tsukamurella',
    'Roseobacter denitrificans': 'Roseobacter',
    'Stenotrophomonas sp.': 'Stenotrophomonas',
    'Pseudoalteromonas sp. Bq0': 'Pseudoalteromonas',
    'Parabacteroides distasonis': 'Parabacteroides',
    'Parabacteroides merdae': 'Parabacteroides',
    'Delftia sp. 670': 'Delftia',
    'Gordonia sp.': 'Gordonia',
    'Gordonia sputi': 'Gordonia',
    'Rhodoferax sp. IMCC26218': 'Rhodoferax',
    'Citrobacter sp. TM1552': 'Citrobacter',
    'Enterobacteriaceae bacterium bta3-1': '',
    'Prochlorococcus marinus': 'Prochlorococcus',
    'Paracoccus marcusii': 'Paracoccus',
    'Limosilactobacillus fermentum': 'Limosilactobacillus',
    'Delftia tsuruhatensis': 'Delftia',
    'Synechococcus sp. CB0101': 'Synechococcus',
    'Synechococcus sp. CB0208': 'Synechococcus',
    'Shewanella sp.': 'Shewanella',
    'Flavobacterium sp.': 'Flavobacterium',
    'Idiomarinaceae bacterium N2-2': '',
    'Idiomarinaceae bacterium M2-2': '',
    'Sulfitobacter sp. CB2047': 'Sulfitobacter',
    'Lelliottia sp. GL2': 'Lelliottia',
    'Dickeya sp.': 'Dickeya',
    'Trichormus variabilis': 'Trichormus',
    'Brucella melitensis': 'Brucella',
    'Brucella canis': 'Brucella',
    'Lactobacillus gasseri': 'Lactobacillus',
    'Microbacterium oxydans': 'Microbacterium',
    'Croceibacter atlanticus': 'Croceibacter',
    'Rhizobium gallicum': 'Rhizobium',
    'Edwardsiella ictaluri': 'Edwardsiella',
    'Enterococcus sp.': 'Enterococcus',
    'Leptolyngbya foveolarum': 'Leptolyngbya',
    'Clavibacter michiganensis': 'Clavibacter',
    'Candidatus Puniceispirillum marinum': 'Candidatus Puniceispirillum',
    'Mycobacterium tuberculosis': 'Mycobacterium',
    'Rhodococcus hoagii': 'Rhodococcus',
    'Mycobacterium avium': 'Mycobacterium',
    'Rhizobium etli': 'Rhizobium',
    'Yersinia pestis': 'Yersinia',
    'Serratia sp.': 'Serratia',
    'Burkholderia cepacia': 'Burkholderia',
    'Acidithiobacillus caldus': 'Acidithiobacillus',
    'Listeria sp.': 'Listeria',
    'Agrobacterium fabacearum': 'Agrobacterium',
    'Weissella cibaria': 'Weissella',
    'Streptomyces sp.': 'Streptomyces',
    'Burkholderia ambifaria': 'Burkholderia',
    'Celeribacter marinus': 'Celeribacter',
    'Saccharomonospora sp.': 'Saccharomonospora',
    'Thermoanaerobacterium saccharolyticum': 'Thermoanaerobacterium',
    'Bifidobacterium bifidum': 'Bifidobacterium',
    'Salisaeta sp. SP9-1': 'Salisaeta',
    'Sphingomonas paucimobilis': 'Sphingomonas',
    'Salinivibrio costicola': 'Salinivibrio',
    'Bdellovibrio bacteriovorus': 'Bdellovibrio',
    'Enterobacter cancerogenus': 'Enterobacter',
    'Staphylococcus hominis': 'Staphylococcus',
    'Planktothrix agardhii': 'Planktothrix',
    'Rhodococcus rhodochrous': 'Rhodococcus',
    'Rhodococcus globerulus': 'Rhodococcus',
    'Nocardia brasiliensis': 'Nocardia',
    'Synechococcus sp. CB0201': 'Synechococcus',
    'Tetrasphaera jenkinsii': 'Tetrasphaera',
    'Pseudomonas tolaasii': 'Pseudomonas',
    'Psychrobacter sp. MV2': 'Psychrobacter',
    'Candidatus Liberibacter asiaticus': 'Liberibacter',
    'Glaesserella parasuis': 'Glaesserella',
    'Synechococcus sp. CB0204': 'Synechococcus',
    'Synechococcus sp. CB0202': 'Synechococcus',
    'Riemerella anatipestifer': 'Riemerella',
    'Lactobacillus sp.': 'Lactobacillus',
    'Synechococcus sp. WH 6501': 'Synechococcus',
    'Synechococcus sp. WH 8017': 'Synechococcus',
    'Synechococcus sp. WH 8101': 'Synechococcus',
    'Pseudoalteromonas sp. H105': 'Pseudoalteromonas',
    'Brochothrix thermosphacta': 'Brochothrix',
    'Aggregatibacter actinomycetemcomitans': 'Aggregatibacter',
    'Streptomyces sp. ZL12': 'Streptomyces',
    'Sodalis glossinidius': 'Sodalis',
    'Delftia acidovorans': 'Delftia',
    'Sulfitobacter sp. EE-36': 'Sulfitobacter',
    'Lactobacillus jensenii': 'Lactobacillus',
    'Candidatus Hamiltonella defensa': 'Candidatus Hamiltonella',
    'Bacteroides fragilis': 'Bacteroides',
    'Iodobacter sp. CdM7': 'Iodobacter',
    'Thalassotalea loyana': 'Thalassotalea',
    'Bacillus sp. 6k512': 'Bacillus',
    'Microbacterium nematophilum': 'Microbacterium',
    'Aeromonas media': 'Aeromonas',
    'Geobacillus sp. 6k51': 'Geobacillus',
    'Kitasatospora aureofaciens': 'Kitasatospora',
    'Chlamydia abortus': 'Chlamydia',
    'Actinomyces naeslundii': 'Actinomyces',
    'Vibrio pelagius': 'Vibrio',
    'Ralstonia pickettii': 'Ralstonia',
    'Synechococcus sp. WH 7805': 'Synechococcus',
    'Myxococcus xanthus': 'Myxococcus',
    'Lactobacillus johnsonii': 'Lactobacillus',
    'Chlamydia pneumoniae': 'Chlamydia',
    'Mycoplasma arthritidis': 'Mycoplasma',
    'Spiroplasma citri': 'Spiroplasma',
    'Mycoplasma sp.': 'Mycoplasma',
    'Aeromonas sp. IS4': 'Aeromonas',
    'Pseudomonas sp. 1-1-1b': 'Pseudomonas',
    'Vibrio sp. 12A10': 'Vibrio',
    'Campylobacter sp.': 'Campylobacter',
    'Aurantimonas sp. C5-1': 'Aurantimonas',
    'Paenibacillus glucanolyticus': 'Paenibacillus',
    'Vibrio sp. YD38': 'Vibrio',
    'Aliivibrio fischeri': 'Aliivibrio',
    'Psychrobacter sp. OW20': 'Psychrobacter',
    'Cellulophaga sp. MM#3': 'Cellulophaga',
    'Vibrio sp. YD21': 'Vibrio',
    'Pseudoalteromonas sp. YD6': 'Pseudoalteromonas',
    'Synechococcus sp. WH 8018': 'Synechococcus',
    'Clostridium perfringens': 'Clostridium',
    'Staphylococcus pasteuri': 'Staphylococcus',
    'Kluyvera cryocrescens': 'Kluyvera',
    'Azospirillum brasilense': 'Azospirillum',
    '[Brevibacterium] flavum': 'Corynebacterium',
    'Synechococcus sp. WH 8012': 'Synechococcus',
    'Clostridium botulinum': 'Clostridium',
    'alpha proteobacterium JL001': '',
    'Evansella clarkii': 'Evansella',
    'Klebsiella oxytoca': 'Klebsiella',
    "Streptococcus sp. 'group C'": 'Streptococcus',
    'Rhodothermus marinus': 'Rhodothermus',
    'Haemophilus influenzae': 'Haemophilus',
    'Acinetobacter genomosp. 16BJ': 'Acinetobacter',
    'Mycoplasmopsis pulmonis': 'Mycoplasmopsis',
    'Chlamydia psittaci': 'Chlamydia',
    'Spiroplasma melliferum': 'Spiroplasma',
    'Acholeplasma laidlawii': 'Acholeplasma',
    'Pseudomonas savastanoi': 'Pseudomonas'
}

genus2family = {
    'Unknown': 'Unknown',
    'Streptococcus': 'Streptococcaceae',
    'Escherichia': 'Enterobacteriaceae',
    'Listeria': 'Listeriaceae',
    'Phaeobacter': 'Roseobacteraceae',
    'Aeromonas': 'Aeromonadaceae',
    'Vibrio': 'Vibrionaceae',
    'Xanthomonas': 'Xanthomonadaceae',
    'Achromobacter': 'Alcaligenaceae',
    'Bacillus': 'Bacillaceae',
    'Mesorhizobium': 'Phyllobacteriaceae',
    'Pantoea': 'Erwiniaceae',
    'Xylella': 'Xanthomonadaceae',
    'Mycolicibacterium': 'Mycobacteriaceae',
    'Gordonia': 'Gordoniaceae',
    'Arthrobacter': 'Micrococcaceae',
    'Streptomyces': 'Streptomycetaceae',
    'Mycobacterium': 'Mycobacteriaceae',
    'Microbacterium': 'Microbacteriaceae',
    'Enterococcus': 'Enterococcaceae',
    'Citrobacter': 'Enterobacteriaceae',
    'Proteus': 'Morganellaceae',
    'Salmonella': 'Enterobacteriaceae',
    'Klebsiella': 'Enterobacteriaceae',
    'Stenotrophomonas': 'Xanthomonadaceae',
    'Synechococcus': 'Synechococcaceae',
    'Parasynechococcus': 'Prochlorococcaceae',
    'Serratia': 'Yersiniaceae',
    'Elizabethkingia': 'Weeksellaceae',
    'Lactococcus': 'Streptococcaceae',
    'Rhodococcus': 'Nocardiaceae',
    'Tenacibaculum': 'Flavobacteriaceae',
    'Pseudoalteromonas': 'Pseudoalteromonadaceae',
    'Ochrobactrum': 'Brucellaceae',
    'Sporosarcina': 'Planococcaceae',
    'Bifidobacterium': 'Bifidobacteriaceae',
    'Edwardsiella': 'Hafniaceae',
    'Brucella': 'Brucellaceae',
    'Alteromonas': 'Alteromonadaceae',
    'Paenibacillus': 'Paenibacillaceae',
    'Enterobacter': 'Enterobacteriaceae',
    'Sphaerotilus': '',
    'Flavobacterium': 'Flavobacteriaceae',
    'Brevundimonas': 'Caulobacteraceae',
    'Butyrivibrio': 'Lachnospiraceae',
    'Pseudomonas': 'Pseudomonadaceae',
    'Pectobacterium': 'Pectobacteriaceae',
    'Shigella': 'Enterobacteriaceae',
    'Geobacillus': 'Bacillaceae',
    'Cutibacterium': 'Propionibacteriaceae',
    'Sinomonas': 'Micrococcaceae',
    'Candidatus Pelagibacter': 'Pelagibacteraceae',
    'Rhizobium': 'Rhizobiaceae',
    'Photobacterium': 'Vibrionaceae',
    'Erwinia': 'Erwiniaceae',
    'Campylobacter': 'Campylobacteraceae',
    'Burkholderia': 'Burkholderiaceae',
    'Leuconostoc': 'Lactobacillaceae',
    'Corynebacterium': 'Corynebacteriaceae',
    'Mycobacteroides': 'Mycobacteriaceae',
    'Yersinia': 'Yersiniaceae',
    'Ralstonia': 'Burkholderiaceae',
    'Rothia': 'Micrococcaceae',
    'Curvibacter': 'Comamonadaceae',
    'Sinorhizobium': 'Rhizobiaceae',
    'Wolbachia': 'Anaplasmataceae',
    'Bordetella': 'Alcaligenaceae',
    'Priestia': 'Bacillaceae',
    'Caulobacter': 'Caulobacteraceae',
    'Acinetobacter': 'Moraxellaceae',
    'Dinoroseobacter': 'Roseobacteraceae',
    'Levilactobacillus': 'Lactobacillaceae',
    'Rheinheimera': 'Chromatiaceae',
    'Shewanella': 'Shewanellaceae',
    'Ligilactobacillus': 'Lactobacillaceae',
    'Raoultella': 'Enterobacteriaceae',
    'Nodularia': 'Aphanizomenonaceae',
    'Agrobacterium': 'Rhizobiaceae',
    'Phocaeicola': 'Bacteroidaceae',
    'Virgibacillus': 'Bacillaceae',
    'Exiguobacterium': '',
    'Fusobacterium': 'Fusobacteriaceae',
    'Microcystis': 'Microcystaceae',
    'Cronobacter': 'Enterobacteriaceae',
    'Meiothermus': 'Thermaceae',
    'Thermus': 'Thermaceae',
    'Providencia': 'Morganellaceae',
    'Thermobifida': 'Nocardiopsaceae',
    'Prevotella': 'Prevotellaceae',
    'Paracoccus': 'Rhodobacteraceae',
    'Alkalihalobacillus': 'Bacillaceae',
    'Lactiplantibacillus': 'Lactobacillaceae',
    'Aerococcus': 'Aerococcaceae',
    'Lentibacter': 'Roseobacteraceae',
    'Lacticaseibacillus': 'Lactobacillaceae',
    'Brevibacterium': 'Brevibacteriaceae',
    'Sutcliffiella': 'Bacillaceae',
    'Marinobacter': 'Marinobacteraceae',
    'Weissella': 'Lactobacillaceae',
    'Dickeya': 'Pectobacteriaceae',
    'Paeniglutamicibacter': 'Micrococcaceae',
    'Limosilactobacillus': 'Lactobacillaceae',
    'Acidovorax': 'Comamonadaceae',
    'unclassified Bacteria': 'unclassified Bacteria',
    'Bacteroides': 'Bacteroidaceae',
    'Mastigocladus': 'Hapalosiphonaceae',
    'Leptospira': 'Leptospiraceae',
    'Eggerthella': 'Eggerthellaceae',
    'Ruegeria': 'Roseobacteraceae',
    'Pasteurella': 'Pasteurellaceae',
    'Oenococcus': 'Lactobacillaceae',
    'Marinomonas': 'Oceanospirillaceae',
    'Clostridioides': 'Peptostreptococcaceae',
    'Anoxybacillus': 'Bacillaceae',
    'Lactobacillus': 'Lactobacillaceae',
    'Schaalia': 'Actinomycetaceae',
    'Nocardia': 'Nocardiaceae',
    'Faecalibacterium': 'Oscillospiraceae',
    'Pontimonas': 'Microbacteriaceae',
    'Gluconobacter': 'Acetobacteraceae',
    'Staphylococcus': 'Staphylococcaceae',
    'Salinibacter': 'Rhodothermaceae',
    'Erysipelothrix': 'Erysipelotrichaceae',
    'Plesiomonas': 'Enterobacteriaceae',
    'Citromicrobium': 'Sphingomonadaceae',
    'Aphanizomenon': 'Aphanizomenonaceae',
    'Lysinibacillus': 'Bacillaceae',
    'Propionibacterium': 'Propionibacteriaceae',
    'Caldibacillus': 'Bacillaceae',
    'Leclercia': 'Enterobacteriaceae',
    'Salicola': 'Halomonadaceae',
    'Liberibacter': 'Rhizobiaceae',
    'Candidatus Xenohaliotis': 'Anaplasmataceae',
    'Tritonibacter': 'Rhodobacteraceae',
    'Bradyrhizobium': 'Bradyrhizobiaceae',
    'Morganella': 'Morganellaceae',
    'Sphingobium': 'Sphingomonadaceae',
    'Candidatus Azobacteroides': '',
    'Helicobacter': 'Helicobacteraceae',
    'Rathayibacter': 'Microbacteriaceae',
    'Erythrobacter': 'Erythrobacteraceae',
    'Aquamicrobium': 'Phyllobacteriaceae',
    'Aeribacillus': 'Bacillaceae',
    'Halomonas': 'Halomonadaceae',
    'Salinivibrio': 'Vibrionaceae',
    'Salipiger': 'Roseobacteraceae',
    'Rhodovulum': 'Rhodobacteraceae',
    'Nostoc': 'Nostocaceae',
    'Tsukamurella': 'Tsukamurellaceae',
    'Marinitoga': 'Petrotogaceae',
    'Acaryochloris': 'Acaryochloridaceae',
    'Cellulophaga': 'Flavobacteriaceae',
    'Moraxella': 'Moraxellaceae',
    'Skermania': 'Gordoniaceae',
    'Hydrogenobaculum': 'Aquificaceae',
    'Mannheimia': 'Pasteurellaceae',
    'Brevibacillus': 'Paenibacillaceae',
    'Prochlorococcus': 'Prochlorococcaceae',
    'Rhodobacter': 'Rhodobacteraceae',
    'Roseobacter': 'Roseobacteraceae',
    'Parabacteroides': 'Tannerellaceae',
    'Polaribacter': 'Flavobacteriaceae',
    'Delftia': 'Comamonadaceae',
    'Rhodoferax': 'Comamonadaceae',
    'Sulfitobacter': 'Roseobacteraceae',
    'Lelliottia': 'Enterobacteriaceae',
    'Trichormus': 'Nostocaceae',
    'Nitrincola': 'Oceanospirillaceae',
    'Croceibacter': 'Flavobacteriaceae',
    'Leptolyngbya': 'Leptolyngbyaceae',
    'Clavibacter': 'Microbacteriaceae',
    'Candidatus Puniceispirillum': '',
    'Acidithiobacillus': 'Acidithiobacillaceae',
    'Celeribacter': 'Roseobacteraceae',
    'Nonlabens': 'Flavobacteriaceae',
    'Saccharomonospora': 'Pseudonocardiaceae',
    'Thermoanaerobacterium': 'Thermoanaerobacterales Family III. Incertae Sedis',
    'Colwellia': 'Colwelliaceae',
    'Salisaeta': 'Salisaetaceae',
    'Sphingomonas': 'Sphingomonadaceae',
    'Bdellovibrio': 'Bdellovibrionaceae',
    'Planktothrix': 'Microcoleaceae',
    'Pediococcus': 'Lactobacillaceae',
    'Tetrasphaera': 'Intrasporangiaceae',
    'Psychrobacter': 'Moraxellaceae',
    'Glaesserella': 'Pasteurellaceae',
    'Riemerella': 'Weeksellaceae',
    'Brochothrix': 'Listeriaceae',
    'Aggregatibacter': 'Pasteurellaceae',
    'Sodalis': 'Bruguierivoracaceae',
    'Kluyvera': 'Enterobacteriaceae',
    'Candidatus Hamiltonella': 'Enterobacteriaceae\t',
    'Iodobacter': 'Chromobacteriaceae',
    'Spiroplasma': 'Spiroplasmataceae',
    'Thalassotalea': 'Colwelliaceae',
    'Phormidium': 'Oscillatoriaceae',
    'Kitasatospora': 'Streptomycetaceae',
    'Chlamydia': 'Chlamydiaceae',
    'Actinomyces': 'Actinomycetaceae',
    'Mycoplasma': 'Mycoplasmataceae',
    'Actinoplanes': 'Micromonosporaceae',
    'Myxococcus': 'Myxococcaceae',
    'Haemophilus': 'Pasteurellaceae',
    'Clostridium': 'Clostridiaceae',
    'Aurantimonas': 'Aurantimonadaceae',
    'Aliivibrio': 'Vibrionaceae',
    'Loktanella': 'Roseobacteraceae',
    'Azospirillum': 'Azospirillaceae',
    'Evansella': 'Bacillaceae',
    'Rhodothermus': 'Rhodothermaceae',
    'Mycoplasmopsis': 'Mycoplasmataceae',
    'Acholeplasma': 'Acholeplasmataceae'
}
